#!/bin/sh

# /usr/local/rvm/rubies/ruby-2.4.1/bin/ruby
# -E LD_DEBUG=all
export DTLS=true
export SERVCERT=db/cert/jrc_prime256v1.crt
export SERVKEY=db/cert/jrc_prime256v1.key
#strace -o /tmp/nn1 -E LD_PRELOAD=/sandel/3rd/openssl/lib/libcrypto.so.1.1:/sandel/3rd/openssl/lib/libssl.so.1.1 ./ruby bin/rails server david -b ::2 -p 5684

#LD_PRELOAD=/sandel/3rd/openssl/lib/libcrypto.so.1.1:/sandel/3rd/openssl/lib/libssl.so.1.1  ./ruby bin/rails server david -b ::2 -p 5684
LD_PRELOAD=/sandel/3rd/openssl-dtls-api/lib/libcrypto.so.1.1:/sandel/3rd/openssl-dtls-api/lib/libssl.so.1.1  ruby bin/rails server david -b :: -p 5684




