# coding: utf-8

"""
    CIRA SHG Windex API

    CIRALabs SecureHomeGateway Windex API: between smartphone and router  # noqa: E501

    OpenAPI spec version: 1.0.0-current
    Contact: securehomegateway@cira.ca
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import client
from client.api.manufacturer_api import ManufacturerApi  # noqa: E501
from client.rest import ApiException


class TestManufacturerApi(unittest.TestCase):
    """ManufacturerApi unit test stubs"""

    def setUp(self):
        self.api = client.api.manufacturer_api.ManufacturerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_manufacturer(self):
        """Test case for create_manufacturer

        Add a new manufacturer  # noqa: E501
        """
        pass

    def test_get_manufacturer(self):
        """Test case for get_manufacturer

        Get a manufacturer information  # noqa: E501
        """
        pass

    def test_list_manufacturers(self):
        """Test case for list_manufacturers

        Get manufacturers  # noqa: E501
        """
        pass

    def test_update_manufacturer(self):
        """Test case for update_manufacturer

        Update an existing manufacturer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
