# coding: utf-8

"""
    CIRA SHG Windex API

    CIRALabs SecureHomeGateway Windex API: between smartphone and router  # noqa: E501

    OpenAPI spec version: 1.0.0-current
    Contact: securehomegateway@cira.ca
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import client
from client.api.device_api import DeviceApi  # noqa: E501
from client.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = client.api.device_api.DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_device(self):
        """Test case for create_device

        Add a new device to the store  # noqa: E501
        """
        pass

    def test_get_device(self):
        """Test case for get_device

        Get a device information  # noqa: E501
        """
        pass

    def test_list_devices(self):
        """Test case for list_devices

        List devices  # noqa: E501
        """
        pass

    def test_update_device(self):
        """Test case for update_device

        Update an existing device  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
