# coding: utf-8

"""
    CIRA SHG Windex API

    CIRALabs SecureHomeGateway Windex API: between smartphone and router  # noqa: E501

    OpenAPI spec version: 1.0.0-current
    Contact: securehomegateway@cira.ca
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import client
from client.api.device_type_api import DeviceTypeApi  # noqa: E501
from client.rest import ApiException


class TestDeviceTypeApi(unittest.TestCase):
    """DeviceTypeApi unit test stubs"""

    def setUp(self):
        self.api = client.api.device_type_api.DeviceTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_device_type(self):
        """Test case for create_device_type

        Add a new device type to the store  # noqa: E501
        """
        pass

    def test_get_device_type(self):
        """Test case for get_device_type

        Get a device type information  # noqa: E501
        """
        pass

    def test_list_device_types(self):
        """Test case for list_device_types

        Get device types  # noqa: E501
        """
        pass

    def test_update_device_type(self):
        """Test case for update_device_type

        Update an existing device type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
