# coding: utf-8

"""
    CIRA SHG Windex API

    CIRALabs SecureHomeGateway Windex API: between smartphone and router  # noqa: E501

    OpenAPI spec version: 1.0.0-current
    Contact: securehomegateway@cira.ca
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import client
from client.models.user_json import UserJson  # noqa: E501
from client.rest import ApiException


class TestUserJson(unittest.TestCase):
    """UserJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserJson(self):
        """Test UserJson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = client.models.user_json.UserJson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
