# coding: utf-8
# this is Docker specific Gemfile
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', "~> 5.2.8.1"

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem "turbolinks"

#gem 'ecdsa',   :path => '/app/minerva/ruby_ecdsa'
gem 'ecdsa',   :git => 'https://github.com/AnimaGUS-minerva/ruby_ecdsa.git', :branch => 'ecdsa_interface_openssl'

#gem 'chariwt', :path => '/app/minerva/chariwt'
gem 'chariwt', :git => 'https://github.com/mcr/ChariWTs.git', :branch => 'v0.9.0'
gem 'jwt'

#gem "fixture_save", :path => "../fixture_save"
gem 'fixture_save', :git => 'https://github.com/mcr/fixture_save.git'

gem 'jbuilder', '~> 2.0'
gem 'rake'

gem 'tzinfo-data'

gem 'mail'
gem 'ffi', '~> 1.14.2'
gem 'bundler', "~> 2.3.11"

# due to alerts
gem "yard", ">= 0.9.20"
gem "websocket-extensions", ">= 0.1.5"
gem "rack", ">= 2.2.3.1"
gem "loofah", ">= 2.3.1"
gem "actionpack", ">= 5.2.6.2"
gem "activerecord", ">= 5.2.8.1"
gem "json", ">= 2.3.0"
gem "rexml", ">= 3.2.5"
gem "addressable", ">= 2.8.0"
gem "nokogiri", ">= 1.13.5"
gem "rails-html-sanitizer", ">= 1.4.3"
gem "tzinfo", ">= 1.2.10"

# Use Capistrano for deployment
gem 'capistrano', '~> 3.11.0', group: :development
gem 'capistrano-rails',  group: :development
gem 'capistrano-rvm',    group: :development
gem 'capistrano-bundler',group: :development

# needs special build instructions, and special openssl.
#gem 'openssl', "~> 2.1.0"
gem 'openssl', :path => '/app/minerva/ruby-openssl'
#gem 'openssl', :path => "../minerva/ruby-openssl"

# CoAP server for Rails.
gem 'coap',    :git => 'https://github.com/AnimaGUS-minerva/coap.git', :branch => 'dtls-client'
#gem 'coap',    :path => "/app/minerva/coap"

gem 'celluloid-io', :git => 'https://github.com/AnimaGUS-minerva/celluloid-io.git', :submodules => true
#gem 'celluloid-io', :path => "/app/minerva/celluloid-io"

#gem 'david', :git => 'https://github.com/AnimaGUS-minerva/david.git'
#gem 'david', :git => 'https://github.com/AnimaGUS-minerva/david.git', :branch => 'dtls-david'

# use this to get full decoding of HTTP Accept: headers, to be able to
# split off smime-type=voucher in pkcs7-mime, and other parameters
gem 'http-accept'

# IP address management for use in ANIMA ACP
gem 'ipaddress'

# encode/decode cbor messages
gem 'cbor'
gem 'rabl'
gem 'oj'

gem 'sqlite3', "~> 1.4.2"
gem 'pg', '~> 0.21'

# used in production on SecureHomeGateway
gem 'thin'
gem 'byebug'

# when passenger is used, it helps to have it built for this very of ruby
gem 'passenger'

# use for background processing of mud files, and interaction with
# mud-controller.
gem 'sucker_punch'
gem 'rb-readline'

